taosdata/.github

- workflows/install-flashmq.yml
> test: add test yml

- .github/workflows/deploy-fractal.yml
> 依据参数动态分配runner并各自运行

- .github/actions/deploy-minio/action.yml
- .github/actions/install-flashmq/action.yml
- .github/actions/install-mqtt-simulator/action.yml
- .github/actions/install-tdengine-enterprise/action.yml
- .github/workflows/deploy-minio.yml
- .github/workflows/deploy-mqtt.yml
- .github/workflows/install-enterprise.yml
- .github/workflows/install-flashmq.yml
- .github/workflows/update-hosts.yml
> feat: add workflows and actions for fractal-test

- .github/actions/install-mqtt-simulator/action.yml
> modify action install-mqtt-simulator

- .github/pull_request_template.md
> chore: update jira info in template

- .github/actions/config-process-exporter-yml/action.yml
- .github/actions/config-prometheus-yml/action.yml
- .github/actions/deploy-minio/action.yml
- .github/actions/deploy-taostest-testng/action.yml
- .github/actions/gen-taostest-env/action.yml
- .github/actions/install-flashmq/action.yml
- .github/actions/install-grafana/action.yml
- .github/actions/install-mqtt-simulator/action.yml
- .github/actions/install-node-exporter/action.yml
- .github/actions/install-process-exporter/action.yml
- .github/actions/install-prometheus/action.yml
- .github/actions/install-tdengine-enterprise/action.yml
- .github/actions/ssh-keyless-login/action.yml
- .github/scripts/config_grafana_anonymous_access.sh
- .github/scripts/config_process_exporter_yml.sh
- .github/scripts/config_prometheus_yml.sh
- .github/scripts/config_ssh_keyless_login.sh
- .github/scripts/deploy_minio.sh
- .github/scripts/install_flashmq.sh
- .github/scripts/install_tdengine_enterprise.sh
Add new actions and scripts.
Jira: https://jira.taosdata.com:18080/browse/TD-33672
> feat: add new actions and scripts

- .github/workflows/run-tests-on-linux.yml
Add clearup step for linux testing workflow
> ci: Add clearup step for linux testing workflow

- .github/workflows/run-tests-on-linux.yml
update workflow to enhance the clearup step for no process found
> ci: update workflow to enhance the clearup step for no process found

- .github/workflows/run-tests-on-linux.yml
remove tdgpt test step and add 'PR-' for restore.sh and run.sh
> ci: remove tdgpt test step and add 'PR-' for restore.sh and run.sh

- .github/workflows/run-tests-on-linux.yml
- .github/workflows/run-tests-on-macos.yml
- .github/workflows/run-tests-on-windows.yml
combine the manual mode into test workflow
- Update linux/mac/windows test workflow to add the manual mode, include the input parameters， env parameters and step logic changes
Jira: https://jira.taosdata.com:18080/browse/TD-34020
> ci: combine the manual mode into test workflow

- .github/workflows/run-tests-on-linux.yml
- .github/workflows/run-tests-on-windows.yml
update test workflow params issue
> ci: update test workflow params issue

- .github/workflows/run-tests-on-linux.yml
update workflow to fix outputs issue of jenkins.log file
> ci: update workflow to fix outputs issue of jenkins.log file

- .github/workflows/run-tests-on-windows.yml
> use python script  in run-tests-on-windows.yml

- .github/workflows/run-coverage-tests-on-linux.yml
> test:add taosd coverage workflow

- .github/workflows/run-coverage-tests-on-linux.yml
> test:alter cov sh

- .github/workflows/run-coverage-tests-on-linux.yml
> test:alter task file

- .github/workflows/run-tests-on-windows.yml
> test：remove cunitest for test

- .github/actions/add-labels/action.yml
- .github/scripts/clone_or_update.sh
- .github/scripts/config_prometheus_yml.sh
- .github/scripts/gen_taostest_env.sh
- .github/scripts/get_runners.sh
- .github/scripts/libs/common.sh
- .github/scripts/update_etc_hosts.sh
Jira: https://jira.taosdata.com:18080/browse/TD-34149
> enh: re-commit some un-merged codes

- .github/workflows/run-tests-on-windows.yml
ci: update taospy version to v2.7.23
Jira: https://jira.taosdata.com:18080/browse/TS-5914
> ci: update taospy version to v2.7.23

- .github/workflows/run-tests-on-linux.yml
> test:add +x run.sh

- .github/workflows/run-tests-on-windows.yml
> enh: add clean up steps for run-tests-on-windows.yml

- .github/scripts/build.py
- .github/scripts/dependencies.txt
- .github/scripts/prepare.py
- .github/scripts/test.py
- .github/scripts/utils.py
- .github/workflows/new-framework-test.yml
> New test framework

- .github/workflows/run-coverage-tests-on-linux.yml
Jira: https://jira.taosdata.com:18080/browse/TD-33983
> test:support coverage test

- .github/actions/deploy-taostest/action.yml
- .github/actions/download-artifacts/action.yml
- .github/actions/dynamic-labels/action.yml
- .github/actions/import-grafana-dashboard/action.yml
- .github/actions/install-mqtt-simulator/action.yml
- .github/actions/upload-host-info/action.yml
- .github/scripts/deploy_taostest.sh
- .github/scripts/gen_taostest_env.sh
- .github/scripts/import_grafana_dashboard.sh
- .github/scripts/install_tdengine_enterprise.sh
- .github/scripts/install_via_apt.sh
Jira: https://jira.taosdata.com:18080/browse/TD-34151
> enh: refactor actions to use workflow in personal repo

- .github/actions/add-pr-labels/action.yml
Get PR number and usr from context rather than inputs.
> refactor: remove two inputs

- .github/actions/add-pr-labels/action.yml
> modify action add-pr-labels

- .github/workflows/run-tests-on-macos.yml
- .github/workflows/run-tests-on-windows.yml
> ci:modify ctest in  run-tests-on-windows.yml

- .github/workflows/run-tests-on-windows.yml
> fix typos in  run-tests-on-windows.yml

- .github/workflows/run-tests-on-macos.yml
- .github/workflows/run-tests-on-windows.yml
> ci:add taosadapter for  windows test

- .github/workflows/run-tests-on-linux.yml
- .github/workflows/run-tests-on-windows.yml
> debug: add log to  run-tests-on-windows.yml

- .github/actions/gen-taostest-env/action.yml
- .github/scripts/gen_taostest_env.sh
> enh: add param for exclude_components

- .github/actions/config-nginx/action.yml
- .github/actions/gen-taostest-env/action.yml
- .github/actions/install-kafka-producer/action.yml
- .github/actions/install-kafka/action.yml
- .github/actions/install-nginx/action.yml
- .github/scripts/config_nginx.sh
- .github/scripts/gen_taostest_env.sh
- .github/scripts/install_kafka.sh
> deploy ngnix, kafka, kafka producer

- .github/actions/add-pr-labels/action.yml
> fix team name error

- .github/actions/install-mqtt-simulator/action.yml
Jira: https://jira.taosdata.com:18080/browse/TS-6495
> feat: use sample data 

- .github/actions/install-mqtt-simulator/action.yml
Jira: https://jira.taosdata.com:18080/browse/TS-6508
> enh: replace longbow with battery_storage_data

- .github/actions/gen-taostest-env/action.yml
- .github/scripts/gen_taostest_env.sh
Jira: https://jira.taosdata.com:18080/browse/TS-6492
> enh: split flashmq from edge node

- .github/scripts/install_kafka.sh
> remove kafka log dir

- .github/workflows/run-tests-on-windows.yml
> Update python connector in run-tests-on-windows.yml

- .github/workflows/tdasset-ci-test.yml
change model folder name from sentence-transformer to huggingface
> change model folder name from sentence-transformer to huggingface

- .github/workflows/tdasset-ci-test.yml
> update workflow opt playwright config

- .github/workflows/tdasset-ci-test.yml
Signed-off-by: WANG Xu <feici02@outlook.com>
Test port 6042 with curl.
> refactor: test port 6042 with curl

- .github/workflows/tdasset-ci-test.yml
> 修改 TDasset CI Workflow 实现

- .github/workflows/run-tests-on-windows.yml
> fix manually test in run-tests-on-windows.yml

- .github/scripts/prepare.py
> fix: restore branch in  prepare.py

- .github/workflows/run-tests-on-windows.yml
> feat: Add support for running army tests in Windows CI workflow

- .github/workflows/run-tests-on-linux.yml
> test：test for ci docker in  run-tests-on-linux.yml

- .github/actions/install-mqtt-emq/action.yml
- .github/actions/install-mqtt-hivemq/action.yml
- .github/actions/install-mqtt-mosquitto/action.yml
- .github/scripts/install_emq.sh
- .github/scripts/install_hivemq.sh
- .github/scripts/install_mosquitto.sh
> feat: add actions and scripts for emq hivemq and mosquitto

- .github/actions/install-flink/action.yml
- .github/actions/install-influxdb/action.yml
- .github/actions/install-kafka/action.yml
- .github/actions/install-mongodb/action.yml
- .github/actions/install-mysql/action.yml
- .github/actions/install-opentsdb/action.yml
- .github/actions/install-pg/action.yml
- .github/scripts/install_flink.sh
- .github/scripts/install_hbase.sh
- .github/scripts/install_influxdb.sh
- .github/scripts/install_jmeter.sh
- .github/scripts/install_kafka.sh
- .github/scripts/install_mongodb.sh
- .github/scripts/install_mysql.sh
- .github/scripts/install_opentsdb.sh
- .github/scripts/install_oracle.sh
- .github/scripts/install_oracle_runInstaller.expect
- .github/scripts/install_pg.sh
github action: install mongodb, kafka, PostgreSQL, Mysql, Oracle，hbase，opentsdb， influxdb，flink
> github action: install mongodb, kafka, PostgreSQL, Mysql, Oracle

- .github/actions/install-flink/action.yml
- .github/actions/install-mongodb/action.yml
- .github/scripts/install_flink.sh
- .github/scripts/install_hbase.sh
- .github/scripts/install_influxdb.sh
- .github/scripts/install_kafka.sh
- .github/scripts/install_mongodb.sh
- .github/scripts/install_mysql.sh
- .github/scripts/install_opentsdb.sh
- .github/scripts/install_oracle.sh
- .github/scripts/install_pg.sh
> optimize action：Mysql，Hbase，flink，Mongodb，pg and oracle

- .github/actions/deploy-superset/README.md
- .github/actions/deploy-superset/action.yml
> add action of superset deployment

- .github/actions/combine-ip-hostname/action.yml
> enh: reorder role_info.json

- .github/actions/install-mssql-server/action.yml
- .github/scripts/install-mssql.sh
Jira: https://jira.taosdata.com:18080/browse/TD-37732
> feat: add github-actions for mssql-server

- .github/workflows/run-tests-on-windows.yml
> Update pip install commands to use Tsinghua mirror

- .github/scripts/test.py
> fix: correct spacing in command for tdgpt test execution

- .github/workflows/test-tdinsight.yml
Jira: https://jira.taosdata.com:18080/browse/TD-None
> test: add test workflow for tdinsight

- .github/scripts/build.py
- .github/scripts/prepare.py
- .github/scripts/test.py
- .github/scripts/utils.py
- .github/workflows/new-framework-test.yml
https://jira.taosdata.com:18080/browse/TD-37521
> enh: enable Windows platform support in new framework tests

- .github/scripts/utils.py
> fix: remove debug print statement in run_command method
